#!/usr/bin/env bash
# Blend matugen palette (/tmp/qs_colors.json) with the active waybar theme,
# emit overriding @define-color lines into ~/.cache/waybar/adaptive-colors.css.
# When wallpaperAdaptive is disabled in settings, write an empty stub instead.

set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/waybar"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/waybar"
SETTINGS="$CONFIG_DIR/waybar-settings.json"
COLORS="/tmp/qs_colors.json"
ACTIVE="$CONFIG_DIR/themes/active.css"
OUT="$CACHE_DIR/adaptive-colors.css"

mkdir -p "$CACHE_DIR"

if [[ ! -f "$SETTINGS" ]]; then
    : >"$OUT"
    exit 0
fi

python3 - "$SETTINGS" "$COLORS" "$ACTIVE" "$OUT" <<'PY'
import json, os, re, sys

settings_path, colors_path, active_path, out_path = sys.argv[1:5]

with open(settings_path) as f:
    s = json.load(f)

if not s.get("wallpaperAdaptive", False):
    open(out_path, "w").close()
    sys.exit(0)

ratio = float(s.get("adaptiveBlendRatio", 0.3))
ratio = max(0.0, min(1.0, ratio))

# Resolve active.css → variant file
real_active = os.path.realpath(active_path)
if not os.path.isfile(real_active):
    open(out_path, "w").close()
    sys.exit(0)

# Parse @define-color wb-NAME #hex
theme = {}
with open(real_active) as f:
    for m in re.finditer(r"@define-color\s+(wb-[a-z\-]+)\s+#([0-9a-fA-F]{6})", f.read()):
        theme[m.group(1)] = m.group(2)

# Load matugen palette (Catppuccin-style names per MatugenColors.qml)
if not os.path.isfile(colors_path):
    open(out_path, "w").close()
    sys.exit(0)
try:
    with open(colors_path) as f:
        mat = json.load(f)
except Exception:
    open(out_path, "w").close()
    sys.exit(0)

# Map waybar names → matugen channel names
mapping = {
    "wb-bg":       "base",
    "wb-bg-dark":  "mantle",
    "wb-fg":       "text",
    "wb-fg-dark":  "subtext1",
    "wb-comment":  "overlay0",
    "wb-blue":     "blue",
    "wb-green":    "green",
    "wb-red":      "red",
    "wb-purple":   "mauve",
    "wb-cyan":     "sapphire",
    "wb-yellow":   "yellow",
    "wb-magenta":  "pink",
    "wb-teal":     "teal",
    "wb-orange":   "peach",
    "wb-border":   "crust",
    "wb-highlight":"surface1",
    "wb-tooltip-bg":"mantle",
}

def hex_to_rgb(h):
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
def rgb_to_hex(rgb):
    return "{:02x}{:02x}{:02x}".format(*[max(0, min(255, int(round(c)))) for c in rgb])
def blend(a, b, t):
    return tuple(a[i] * (1 - t) + b[i] * t for i in range(3))

lines = []
for wb_name, mat_name in mapping.items():
    if wb_name not in theme: continue
    mat_hex = mat.get(mat_name)
    if not mat_hex or not isinstance(mat_hex, str): continue
    mat_hex = mat_hex.lstrip("#")
    if len(mat_hex) != 6: continue
    blended = rgb_to_hex(blend(hex_to_rgb(theme[wb_name]), hex_to_rgb(mat_hex), ratio))
    lines.append(f"@define-color {wb_name} #{blended};")

with open(out_path, "w") as f:
    f.write("/* Generated by wallpaper-adapt.sh — do not edit */\n")
    f.write("\n".join(lines) + "\n")
PY

# Trigger waybar reload
touch "$CONFIG_DIR/style.css"
